### ISSUE TITLE
能否稍微调整一下仓库描述以便优化SEO搜索

### ISSUE THREAD

**Issue by Patrick-Ze** [RichardGuyNotFavMHY/RichardData#1]
感谢大佬对这些数据进行的存档，以后有人岁月史树也不会没有对证了。
提一个小小的建议，能否优化一下仓库的描述，例如`NGA原神版 里茶馆 存档 (archive)`，以便在使用搜索引擎以及Github搜索时能方便地寻找到这个仓库？
当前的仓库描述是`RichardData, archive only`，导致无论是搜`NGA`还是搜`里茶馆`都不会导向这个仓库。我是曾经路过这个仓库，印象中记得仓库名字是与“里茶馆”发音相近的一个英文，最后才在历史记录里找回这个仓库的。如果曾经没有访问过这个仓库，即使有人想找一下是否有相关存档，也比较难找到这里。
![image](https://github.com/RichardGuyNotFavMHY/RichardData/assets/19711799/3ec5f1c2-7fd5-4d60-84e9-d93e0794d100)

感谢～

**Comment by RichardGuyNotFavMHY** [comment]
您的建议我已经看到，会找时间做优化。
